### ISSUE TITLE
need api for giving trait score in trait details page

### ISSUE THREAD

**Issue by DhakateYuvraj** [subhradip82/wesayweb#11]
api -> userzone/customPoints/
input ->  {traituniqueid: trait.trait_id,traitname: trait.traitname,traitgivenfor: '0',sliderValue: this.sliderValue,}
output -> success / error

**Comment by subhradip82** [comment]
Lonik to https://github.com/subhradip82/wesayweb/issues/4

**Comment by subhradip82** [comment]
As it will be handled in https://github.com/subhradip82/wesayweb/issues/4 , closing this one
